name: app submissions

on:
  pull_request:
    branches:
      - main
#    paths:
#      - 'packages/**'

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          python3 -m pip install -r ./requirements.txt
          python3 -m pip install yq
          npm install -g @webosbrew/compat-checker

      - name: Check changed packages
        uses: dorny/paths-filter@v2
        id: changed_files
        with:
          list-files: shell

          filters: |
            packages:
              - added|modified: 'packages/**'

      - name: Lint package information
        id: lint_package
        if: ${{ steps.changed_files.outputs.packages == 'true' }}
        run: |
          for changed_file in ${{ steps.changed_files.outputs.packages_files }}; do
            python3 -m repogen.lintpkg -f ${changed_file}
            filehash=$(sha256sum "${changed_file}" | cut -d ' ' -f 1)
            ipkfile=/tmp/${filehash}.ipk
            python3 -m repogen.downloadipk -i ${changed_file} -o "${ipkfile}"
            validation_result=$(webosbrew-ipk-compat-checker -m "${ipkfile}")
            echo "::set-output name=validation_result_${filehash}::${validation_result}"
          done

      - name: Report check result
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
             console.log("${{ steps.changed_files.outputs.packages_files }}".split(' '))
#            github.rest.issues.createComment({
#              issue_number: context.issue.number,
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              body: '👋 Thanks for reporting!'
#            })