name: app submissions

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt

      - name: Check changed packages
        uses: dorny/paths-filter@v2
        id: changed_files
        with:
          list-files: shell

          filters: |
            packages:
              - added|modified: 'packages/**'

      - name: Lint package information
        if: ${{ steps.changed_files.outputs.packages == 'true' }}
        run: |
          for changed_file in ${{ steps.changed_files.outputs.packages_files }}; do
            echo "Check package info ${changed_file}."
          done